// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import './src/config/env.js'

export default defineConfig({
  schema: "./src/models/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "./src/seeder/seed.js",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
